name: MaxDeploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [maxdeploy_run]
  schedule:
    - cron: "30 * * * *"   # Deploy 30 minutes past every hour

jobs:
  deploy-products:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build Deployment Artifacts
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist

      - name: Summary
        run: echo "MaxDeploy published the latest product to production."
